eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info 
info:
  author: Fernando L. L. Carvalho
  mail: f.luiz1996@gmail.com
server:
  port: 9999  
message: Configuração cetralizada com spring cloud config

