server:
  port: 8082
spring:
    datasource:
        username: root
        password: ${DATA_BASE_PASSWORD:Cgx1123581321}
        url: "jdbc:mysql://localhost:3306/provajava"
    jpa:
      hibernate:
        ddl-auto: update
